site:
  title: FoodTruckNerdz Documentation
  url: https://docs.foodtrucknerdz.com
  start_page: docs::index.adoc
content:
  sources:
    - url: https://github.com/FoodTruckNerds/onboarding.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/food-truck-api.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/ftn-site.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/ftn-site-old.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/docs.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/help.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/FoodTruckNerds/developer-portal.git
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/the-dev-center/antora-dark-theme/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./site/supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-emoji
  attributes:
    # Organization URLs
    github-org: FoodTruckNerds
    github-org-url: https://github.com/FoodTruckNerds
    docs-site-url: https://docs.foodtrucknerdz.com
    # Repository names
    repo-docs: docs
    repo-ftn-site: ftn-site
    repo-food-truck-api: food-truck-api
    repo-onboarding: onboarding
    repo-help: help
    repo-developer-portal: developer-portal
    repo-ftn-site-old: ftn-site-old
