site:
  title: FoodTruckNerdz Documentation
  url: https://docs.foodtrucknerdz.com
  start_page: onboarding::index.adoc
content:
  sources:
    - url: ../../onboarding
      branches: HEAD
      start_path: docs
    - url: ../../food-truck-api
      branches: HEAD
      start_path: docs
    - url: ../../ftn-site-vercel
      branches: HEAD
      start_path: docs
    - url: ../../FoodTruckNerdzSite
      branches: HEAD
      start_path: docs
    - url: ..
      branches: HEAD
      start_path: docs
    - url: ../../help
      branches: HEAD
      start_path: docs
    - url: ../../developer-portal
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/the-dev-center/antora-dark-theme/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  extensions:
    - asciidoctor-emoji
